name: Setup and Install deps
description: Setup Node.js/pnpm. Install dependencies.
runs:
  using: "composite"
  steps:
    - run: corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
    - name: Install deps
      run: pnpm install
      shell: bash
